version: '2.7.2'
services:
  db:
    image: postgres:14.2-alpine
    container_name: demo-postgres-14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB = bugzilla_production
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=test123
    ports:
      - "5432:5432"
  demo-web:
    build: .
    command: "./bin/rails server"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=bugzilla_production
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=test123
      - RAILS_MASTER_KEY=cc8b322b141f10e1a2ef45fcd1c488e7
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  postgres_data: {}
  app-storage: {}
