
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: test123
  host: localhost

development:
  <<: *default
  database: bugzilla_development
test:
  <<: *default
  database: bugzilla_test
  
production:
  <<: *default
  database: bugzilla_production
  username: root
  password: test123
